#!/bin/sh
# File generated by ocamlbuild

cd /home/fso/eclipse-workspace/P1

rm -f Genealogy.cmi
rm -f Genealogy.cmo
# Also clean the script itself
rm -f /home/fso/eclipse-workspace/P1/_build/sanitize.sh
